# slowfast_8x8_resnet101_kinetics400

DDP_CONFIG:
  WORLD_SIZE: 1
  WORLD_RANK: 0
  GPU_WORLD_SIZE: 8
  GPU_WORLD_RANK: 0
  DIST_URL: 'tcp://172.31.72.195:23456'
  WOLRD_URLS: ['172.31.72.195']
  AUTO_RANK_MATCH: True
  DIST_BACKEND: 'nccl'
  GPU: 0
  DISTRIBUTED: True

CONFIG:
  TRAIN:
    EPOCH_NUM: 196
    BATCH_SIZE: 8
    LR: 0.01
    MOMENTUM: 0.9
    W_DECAY: 1e-5
    USE_WARMUP: True
    WARMUP_EPOCHS: 34
    LR_POLICY: 'Cosine'
    WARMUP_END_LR: 0.1
    RESUME_EPOCH: -1

  VAL:
    FREQ: 2
    BATCH_SIZE: 8

  DATA:
    TRAIN_ANNO_PATH: '/home/ubuntu/data/kinetics400/k400_train.txt'
    VAL_ANNO_PATH: '/home/ubuntu/data/kinetics400/k400_val.txt'
    TRAIN_DATA_PATH: '/home/ubuntu/data/kinetics400/train_256/'
    VAL_DATA_PATH:  '/home/ubuntu/data/kinetics400/val_256/'
    NUM_CLASSES: 400
    CLIP_LEN: 32
    FRAME_RATE: 2
    NUM_SEGMENT: 1
    NUM_CROP: 1
    TEST_NUM_SEGMENT: 10
    TEST_NUM_CROP: 3
    MULTIGRID: False
    KEEP_ASPECT_RATIO: False

  MODEL:
    NAME: 'slowfast_8x8_resnet101_kinetics400'
    PRETRAINED: False

  LOG:
    BASE_PATH: './logs/slowfast_8x8_resnet101_kinetics400'
    LOG_DIR: 'tb_log'
    SAVE_DIR: 'checkpoints'
    EVAL_DIR: './logs/slowfast_8x8_resnet101_kinetics400/eval'
    SAVE_FREQ: 2
